apiVersion: v1
kind: Pod
metadata:
  name: samsara-pod
  labels:
    name: samsara
    app: samsara
spec:
  containers:
  - name: samsara
    image: 370535134506.dkr.ecr.us-west-2.amazonaws.com/samsara:latest
    ports:
      - containerPort: 9000
  - name: db
    image: 370535134506.dkr.ecr.us-west-2.amazonaws.com/db:latest
    ports:
      - containerPort: 5432
    volumeMounts:
       - mountPath: /var/lib/postgresql/data
         name: psql-data
  volumes:
  - name: psql-data
  initContainers:
  - name: init-db
    image: busybox
    command: ['sh', '-c', 'until nslookup db-service; do echo "waiting for db"; sleep 10; done;']