#!/usr/bin/env ansible-playbook
- name: Configure developer environment with JDK and PostgreSQL
  hosts: ansible_vagrant
  sudo: True
  vars_files:
    - ../conf/myvar.yml
    - ../conf/vault.yml
  tasks:
  #  - name: Get vagrant ip-address
  #  - debug: "var={{ db.host['vagrant'] }}"
    - pip:
        name: boto3

    - name: Obtain database URL from AWS RDS
      rds:
        command=facts
        instance_name=auradb
        region=us-west-2
        aws_access_key={{ aws_access_key }}
        aws_secret_key={{ aws_secret_key }}
      register: rds_facts
      until: not(rds_facts.instance.endpoint is none)
      retries: 20
      delay: 30

    - debug: var=rds_facts
    - debug: var=db_host

    - set_fact:
        db_host: "{{ rds_facts.instance.endpoint }}"

    - debug: var=db_host