# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

# Vagrant cannot be used with Ubuntu/Focal at the moment, due to the removal of the traditional
# networking configuration tools and files: /sbin/ifup and /sbin/ifdown.
# Workaround: use bento/ubuntu-20.04 box instead of ubuntu/focal
  config.vm.box = "ubuntu/bionic64"

  config.vm.network :forwarded_port, guest: 5432, host: 5432, auto_correct:true
  config.vm.network :forwarded_port, guest: 9000, host: 9000, auto_correct:true

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "../../", "/home/vagrant/demo1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision :shell, path: "vagrant_init.sh", privileged: false
   
end
