apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-11-04T18:36:19Z
  name: demo3-cluster.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://demo3-kops-state/demo3-cluster.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
      volumeSize: 4
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
      volumeSize: 4
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.7.4
  masterPublicName: api.demo3-cluster.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Public
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-11-04T18:36:19Z
  labels:
    kops.k8s.io/cluster: demo3-cluster.k8s.local
  name: master-us-west-2a
spec:
  image: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28
  machineType: t2.micro
  maxSize: 2
  minSize: 2
  role: Master
  rootVolumeSize: 8
  subnets:
  - us-west-2a

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-11-04T18:36:19Z
  labels:
    kops.k8s.io/cluster: demo3-cluster.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28
  machineType: t2.micro
  maxSize: 2
  minSize: 2
  role: Node
  rootVolumeSize: 8
  subnets:
  - us-west-2a

