apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  ports:
    - port: 5000
      targetPort: 443
      name: registry-port
  selector:
    app: registry
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-storage
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/registry

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-vol-claim
  labels:
    app: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - image: registry:latest
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 443
          name: registry-port
        env:
          - name: REGISTRY_HTTP_ADDR
            value: "0.0.0.0:443"
          - name: REGISTRY_HTTP_HOST
            value: https://{{registry_url}}
          - name: REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE
            value: /etc/docker/registry/letsencrypt.json
          - name: REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL
            value: lerkasan@gmail.com
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
      volumes:
      - name: registry-storage
        persistentVolumeClaim:
          claimName: registry-vol-claim
