apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  ports:
    - port: 5000
      name: registry-port
    - port: 443
      name: registry-ui
  selector:
    app: registry
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-storage
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/registry

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-vol-claim
  labels:
    app: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: registry-port
        env:
          - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
            value: /var/lib/registry
          - name: REGISTRY_HTTP_ADDR
            value: 0.0.0.0:5000
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: /cert/fullchain.pem
          - name: REGISTRY_HTTP_TLS_KEY
            value: /cert/privkey.pem
          - name: REGISTRY_AUTH
            value: htpasswd
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: "Registry Realm"
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: /auth/htpasswd
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
        - name: tls-certs-back
          mountPath: /cert
        - name: auth
          mountPath: /auth/htpasswd
      - name: registry-ui
        image: konradkleine/docker-registry-frontend:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 443
          name: registry-ui
          protocol: TCP
        env:
          - name: ENV_DOCKER_REGISTRY_HOST
            value: "localhost"
          - name: ENV_DOCKER_REGISTRY_PORT
            value: "5000"
          - name: ENV_DOCKER_REGISTRY_USE_SSL
            value: "1"
          - name: ENV_USE_SSL
            value: "yes"
        volumeMounts:
        - name: tls-cert-front
          mountPath: /etc/apache2/server.crt
        - name: tls-key-front
          mountPath: /etc/apache2/server.key
      volumes:
      - name: registry-storage
        persistentVolumeClaim:
          claimName: registry-vol-claim
      - name: tls-certs-back
        hostPath:
          path: /home/admin
      - name: tls-cert-front
        hostPath:
          path: /home/admin/server.crt
      - name: tls-key-front
        hostPath:
          path: /home/admin/server.key
      - name: auth
        hostPath:
          path: /home/admin/htpasswd
#          type: Directory
#      - name: tls-cert
#        awsElasticBlockStore:
#          volumeID: aws://us-west-2a/vol-0fce34e488cf98509
#          fsType: ext4